### ISSUE TITLE
NotFoundException thrown for BotAlias name

### ISSUE THREAD

**Issue by vijayasankar** [aws-samples/amazon-lex-bot-test#1]
Hi,

I used the teslexbot.js file  from here to test our chatbot with modified tests in json file. But I get the Notfoundexception. 

-----------------------test.json file below---------------------------------------------

{
	"name": "KotahiBot-main",
	"description": "Regression tests for the Kotahi bot",
	"botName": "KotahiChatbot_Redo",
	"botAlias": "BETA",
	"waitBetweenRequestsMillis": 0,
	"sequences": [{
		"name": "Hello_Kotahi",
		"description": "Greetings from Kotahi Chatbot",
		"sequence": [{
				"utterance": "Hi",
				"postConditions": {
					"message": ["Hi! I'm your Kotahi chatbotassistant!"]
				}
			},
			{
				"utterance": "where is my container",
				"postConditions": {
					"message": ["Sure! What is your case number\\?"]
				}
			},
			{
				"utterance": "00000102",
				"postConditions": {
					"message": ["I'm sorry. Unexpected problem occurred while I was searching for your case. Please call our service center."]
				}
			}
		]
	}]
}
-----------------------------See the error log here..--------------------------------

$ node testlexbot.js test/test1.json
I Running test cases from test/test1.json for KotahiChatbot_Redo:TERMINATOR - KotahiBot-main
I Test sequence 1 / 1 - Hello_Kotahi
botAlias:  TERMINATOR
-  Sequence [undefined] FAILED! ~ {"message":"postText call failed with NotFoundException: There is no alias named TERMINATOR for the bot named K
otahiChatbot_Redo. Choose another alias.","requestId":null,"sequence":{"utterance":"Hi","postConditions":{"message":["Hi! I'm your Kotahi chatbot
assistant!"]}},"params":{"botAlias":"TERMINATOR","botName":"KotahiChatbot_Redo","userId":"KotahiChatbot_Redo-Hello_Kotahi-1526512000361","session
Attributes":{},"inputText":"Hi"},"lexResponse":null}
{ NotFoundException: There is no alias named TERMINATOR for the bot named KotahiChatbot_Redo. Choose another alias.
    at Object.extractError (C:\Alexa\Hive\kotahi_chatbot\node_modules\aws-sdk\lib\protocol\json.js:48:27)
    at Request.extractError (C:\Alexa\Hive\kotahi_chatbot\node_modules\aws-sdk\lib\protocol\rest_json.js:52:8)
    at Request.callListeners (C:\Alexa\Hive\kotahi_chatbot\node_modules\aws-sdk\lib\sequential_executor.js:105:20)
    at Request.emit (C:\Alexa\Hive\kotahi_chatbot\node_modules\aws-sdk\lib\sequential_executor.js:77:10)
    at Request.emit (C:\Alexa\Hive\kotahi_chatbot\node_modules\aws-sdk\lib\request.js:683:14)
    at Request.transition (C:\Alexa\Hive\kotahi_chatbot\node_modules\aws-sdk\lib\request.js:22:10)
    at AcceptorStateMachine.runTo (C:\Alexa\Hive\kotahi_chatbot\node_modules\aws-sdk\lib\state_machine.js:14:12)
    at C:\Alexa\Hive\kotahi_chatbot\node_modules\aws-sdk\lib\state_machine.js:26:10
    at Request.<anonymous> (C:\Alexa\Hive\kotahi_chatbot\node_modules\aws-sdk\lib\request.js:38:9)
    at Request.<anonymous> (C:\Alexa\Hive\kotahi_chatbot\node_modules\aws-sdk\lib\request.js:685:12)
  message: 'There is no alias named TERMINATOR for the bot named KotahiChatbot_Redo. Choose another alias.',
  code: 'NotFoundException',
  time: 2018-05-16T23:06:41.223Z,
  requestId: 'cb3419c5-595d-11e8-8caa-ebda79e2c29f',
  statusCode: 404,
  retryable: false,
  retryDelay: 83.07497330243108 } 'NotFoundException: There is no alias named TERMINATOR for the bot named KotahiChatbot_Redo. Choose another ali
as.\n    at Object.extractError (C:\\Alexa\\Hive\\kotahi_chatbot\\node_modules\\aws-sdk\\lib\\protocol\\json.js:48:27)\n    at Request.extractErr
or (C:\\Alexa\\Hive\\kotahi_chatbot\\node_modules\\aws-sdk\\lib\\protocol\\rest_json.js:52:8)\n    at Request.callListeners (C:\\Alexa\\Hive\\kot
ahi_chatbot\\node_modules\\aws-sdk\\lib\\sequential_executor.js:105:20)\n    at Request.emit (C:\\Alexa\\Hive\\kotahi_chatbot\\node_modules\\aws-
sdk\\lib\\sequential_executor.js:77:10)\n    at Request.emit (C:\\Alexa\\Hive\\kotahi_chatbot\\node_modules\\aws-sdk\\lib\\request.js:683:14)\n
  at Request.transition (C:\\Alexa\\Hive\\kotahi_chatbot\\node_modules\\aws-sdk\\lib\\request.js:22:10)\n    at AcceptorStateMachine.runTo (C:\\A
lexa\\Hive\\kotahi_chatbot\\node_modules\\aws-sdk\\lib\\state_machine.js:14:12)\n    at C:\\Alexa\\Hive\\kotahi_chatbot\\node_modules\\aws-sdk\\l
ib\\state_machine.js:26:10\n    at Request.<anonymous> (C:\\Alexa\\Hive\\kotahi_chatbot\\node_modules\\aws-sdk\\lib\\request.js:38:9)\n    at Req
uest.<anonymous> (C:\\Alexa\\Hive\\kotahi_chatbot\\node_modules\\aws-sdk\\lib\\request.js:685:12)'

**Comment by vijayasankar** [comment]
Bot name :  KotahiChatbot_Redo 
Aliases : BETA
 
TERMINATOR
 
TEST

**Comment by nhira** [comment]
I'm a little confused here... does test1.json (which is what you seem to be using in the command line) refer to BETA or TERMINATOR?
Perhaps the easiest way to confirm this would be to use the CLI to invoke post-text to confirm that the alias you're hoping to use is accessible.
aws lex-runtime post-text --bot-name ...

Hope this helps.

**Comment by unnikrishnan-anil** [comment]
any update on this? Facing the same issue.

**Comment by EightRice** [comment]
I'm getting this too. What's up?

**Comment by bdhakad** [comment]
anyone found fix or cause for this?

**Comment by Lautaroef** [comment]
I'm encountering the same issue

**Comment by grand1nqu1s1tor** [comment]
Any Solutions found?
